# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Flask CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs: 
  test-and-build-ubuntu:
      runs-on: ubuntu-20.04
      steps: 
        - name: Checkout Code 
          uses: actions/checkout@v3
        - name: Sey up python
          uses: actions/setup-python@v3
          with:
            python-version: "3.9"
        - name: Install Make 
          run: sudo apt-get update && sudo apt-get install make 
        - name: Create env Virtual && Run Testes 
          run: make venv && make test
        - uses: mr-smithers-excellent/docker-build-push@v6
          name: Build & push Docker image
          with:
            image: dockermohcine/test-app
            tags: v1
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          